export enum Genre {
    ACTION = 'Action',
    ADVENTURE = 'Adventure',
    ANIMATION = 'Animation',
    BIOGRAPHY = 'Biography',
    COMEDY = 'Comedy',
    CRIME = 'Crime',
    DRAMA = 'Drama',
    FAMILY = 'Family',
    FANTASY = 'Fantasy',
    FILM_NOIR = 'Film Noir',
    HISTORY = 'History',
    HORROR = 'Horror',
    MUSIC = 'Music',
    MUSICAL = 'Musical',
    MYSTERY = 'Mystery',
    ROMANCE = 'Romance',
    SCI_FI = 'Sci-Fi',
    SPORT = 'Sport',
    SUPERHERO = 'Superhero',
    THRILLER = 'Thriller',
    WAR = 'War',
    WESTERN = 'Western'
}